import "codemirror/addon/mode/simple"
const CodeMirror = require("codemirror");

CodeMirror.defineSimpleMode("hlscripts", {
  // The start state contains the rules that are intially used
  start: [
    // The regex matches the token, the token property contains the type
    { regex: /"(?:[^\\]|\\.)*?(?:"|$)/, token: "string" },
    // You can match multiple tokens at once. Note that the captured
    // groups must span the whole string in this case
    // Rules are matched in the order in which they appear, so there is
    // no ambiguity between this one and the one above
    {
      regex: /(?:function|var|return|if|for|while|else|do|this|(bxt[^\s]*?))\b/,
      token: "keyword"
    },
    { regex: /true|false|null|undefined/, token: "atom" },
    {
      regex: /0x[a-f\d]+|[-+]?(?:\.\d+|\d+\.?\d*)(?:e[-+]?\d+)?/i,
      token: "number"
    },
    { regex: /\/\/.*/, token: "comment" },
    { regex: /\/(?:[^\\]|\\.)*?\//, token: "variable-3" },
    // A next property will cause the mode to move to a different state
    { regex: /\/\*/, token: "comment", next: "comment" },
    { regex: /[-+\/*=<>!]+/, token: "operator" },
    // indent and dedent properties guide autoindentation
    { regex: /[\{\[\(]/, indent: true },
    { regex: /[\}\]\)]/, dedent: true },
    { regex: /[a-z$][\w$]*|[A-Z$][\w$]*/, token: "variable" },
    // You can embed other modes with the mode property. This rule
    // causes all code between << and >> to be highlighted with the XML
    // mode.
    { regex: /<</, token: "meta", mode: { spec: "xml", end: />>/ } }
  ],
  // The multi-line comment state.
  comment: [
    { regex: /.*?\*\//, token: "comment", next: "start" },
    { regex: /.*/, token: "comment" }
  ],
  // The meta property contains global information about the mode. It
  // can contain properties like lineComment, which are supported by
  // all modes, and also directives like dontIndentStates, which are
  // specific to simple modes.
  meta: {
    dontIndentStates: ["comment"],
    lineComment: "//"
  }
});

CodeMirror.registerHelper("hintWords",
  "hlscripts",
  ["+alt1", "+attack", "+attack2", "+back", "+break", "+camdistance", "+camin", "+cammousemove", "+camout", "+campitchdown", "+campitchup", "+camyawleft", "+camyawright", "+commandmenu", "+duck", "+forward", "+graph", "+jlook", "+jump", "+klook", "+left", "+lookdown", "+lookup", "+mlook", "+movedown", "+moveleft", "+moveright", "+moveup", "+reload", "+right", "+score", "+showscores", "+speed", "+strafe", "+use", "addip", "alias", "ambient_fade", "ambient_level", "appenddemo", "autosave", "banid", "bgetmod", "bgmbuffer", "bgmvolume", "bind", "bitmapfonts", "bottomcolor", "brightness", "cam_command", "cam_contain", "cam_idealdist", "cam_idealpitch", "cam_idealyaw", "cam_snapto", "cancelselect", "cd", "centerview", "changelevel", "changelevel2", "chase_active", "chase_back", "chase_right",
   "chase_up", "clear", "clientport", "cl_allowdownload", "cl_allowupload", "cl_allow_download", "cl_allow_upload", "cl_anglespeedkey", "cl_backspeed", "cl_bob", "cl_bobcycle", "cl_bobup", "cl_clockreset", "cl_cmdbackup", "cl_cmdrate", "cl_dlmax", "cl_download_ingame", "cl_fixtimerate", "cl_forwardspeed", "cl_gaitestimation", "cl_gg", "cl_gibcount", "cl_giblife", "cl_gibvelscale", "cl_hightrack", "cl_himodels", "cl_idealpitchscale", "cl_latency", "cl_lb", "cl_lc", "cl_lw", "cl_messages", "cl_movespeedkey", "cl_needinstanced", "cl_nopred", "cl_nosmooth", "cl_pitchdown", "cl_pitchspeed", "cl_pitchup", "cl_rate", "cl_resend", "cl_showerror", "cl_showevents", "cl_showfps", "cl_showmessages", "cl_shownet", "cl_sidespeed", "cl_slist", "cl_smoothtime", "cl_solid_players", "cl_spectator_password",
    "cl_timeout", "cl_updaterate", "cl_upspeed", "cl_vsmoothing", "cl_waterdist", "cl_yawspeed", "cmd", "cmdline", "cmdlist", "com_filewarning", "condebug", "condump", "connect", "console", "contimes", "con_color", "con_notifytime", "coop", "crosshair", "cr_demoman", "cr_engineer", "cr_hwguy", "cr_medic", "cr_pyro", "cr_random", "cr_scout", "cr_sniper", "cr_soldier", "cr_spy", "cvarlist", "c_maxdistance", "c_maxpitch", "c_maxyaw", "c_mindistance", "c_minpitch", "c_minyaw", "deathmatch", "decalfrequency", "default_fov", "delta_clear", "delta_stats", "demos", "developer", "direct", "disconnect", "dlfile", "dropclient", "dropitems", "d_spriteskip", "echo", "edgefriction", "endmovie", "entities", "envmap", "escape", "exec", "exit", "ex_correct", "ex_diminishextrap", "ex_extrapmax", "ex_interp",
     "ex_maxaccel", "ex_maxerrordistance", "ex_maxspeed", "ex_minvelocity", "fakelag", "fakeloss", "firstperson", "flush", "fly", "ForceCloseCommand", "force_centerview", "fov", "fps_lan", "fps_max", "fps_modem", "fps_single", "fullinfo", "fullserverinfo", "gamedir", "gamma", "getcertificate", "gg", "give", "gl_affinemodels", "gl_alphamin", "gl_clear", "gl_cull", "gl_d3dflip", "gl_dither", "gl_dump", "gl_flipmatrix", "gl_keeptjunctions", "gl_lightholes", "gl_log", "gl_max_size", "gl_monolights", "gl_nobind", "gl_nocolors", "gl_overbright", "gl_palette_tex", "gl_picmip", "gl_playermip", "gl_polyoffset", "gl_reporttjunctions", "gl_round_down", "gl_smoothmodels", "gl_spriteblend", "gl_texels", "gl_texsort", "gl_texturemode", "gl_wateramp", "gl_zmax", "gl_ztrick", "god", "graphheight", "heartbeat",
      "hideconsole", "hisound", "HostMap", "hostname", "hostport", "host_framerate", "host_limitlocal", "host_profile", "host_speeds", "hpkextract", "hpklist", "hpkremove", "hpkval", "hud_capturemouse", "hud_centerid", "hud_classautokill", "hud_deathnotice_time", "hud_drawhistory_time", "hud_fastswitch", "hud_saytext_time", "hud_takesshots", "impulse", "interp", "invnext", "invprev", "ip", "ipx_clientport", "ipx_hostport", "ip_clientport", "ip_hostport", "joyadvanced", "joyadvancedupdate", "joyadvaxisr", "joyadvaxisu", "joyadvaxisv", "joyadvaxisx", "joyadvaxisy", "joyadvaxisz", "joyforwardsensitivity", "joyforwardthreshold", "joyname", "joypitchsensitivity", "joypitchthreshold", "joysidesensitivity", "joysidethreshold", "joystick", "joywwhack1", "joywwhack2", "joyyawsensitivity", "joyyawthreshold",
       "kick", "kill", "lambert", "lcd_x", "lcd_yaw", "lightgamma", "list", "listdemo", "listid", "listip", "load", "loadas8bit", "localinfo", "log", "logaddress", "lookspring", "lookstrafe", "lservercfgfile", "map", "mapcyclefile", "maps", "maxplayers", "mcache", "messagemode", "messagemode2", "model", "motd", "mp_allowmonsters", "mp_autocrosshair", "mp_consistency", "mp_decals", "mp_defaultteam", "mp_falldamage", "mp_flashlight", "mp_footsteps", "mp_forcerespawn", "mp_fraglimit", "mp_friendlyfire", "mp_logecho", "mp_logfile", "mp_teamlist", "mp_teamoverride", "mp_teamplay", "mp_timelimit", "mp_weaponstay", "m_filter", "m_forward", "m_pitch", "m_side", "m_yaw", "name", "net_address", "net_chokeloop", "net_drawslider", "net_graph", "net_graphpos", "net_graphsolid", "net_graphwidth", "net_scale", "net_showdrop",
        "net_showpackets", "new", "noclip", "nosound", "notarget", "password", "path", "pausable", "pause", "ping", "pingservers", "play", "playdemo", "playvol", "pointfile", "port", "ppdemostart", "precache", "ptrack", "pushlatency", "quit", "rate", "rcon", "rcon_address", "rcon_password", "rcon_port", "reconnect", "record", "reload", "removedemo", "removeid", "removeip", "restart", "retry", "room_delay", "room_dlylp", "room_feedback", "room_left", "room_lp", "room_mod", "room_off", "room_refl", "room_rvblp", "room_size", "room_type", "r_bmodelhighfrac", "r_bmodelinterp", "r_cachestudio", "r_decals", "r_drawentities", "r_drawviewmodel", "r_dynamic", "r_fullbright", "r_glowshellfreq", "r_lightmap", "r_mirroralpha", "r_mmx", "r_netgraph", "r_norefresh", "r_novis", "r_shadows", "r_speeds", "r_traceglow", "r_wadtextures",
         "r_wateralpha", "save", "say", "say_team", "screenshot", "scr_centertime", "scr_connectmsg", "scr_connectmsg1", "scr_connectmsg2", "scr_conspeed", "scr_ofsx", "scr_ofsy", "scr_ofsz", "scr_printspeed", "sendents", "sensitivity", "servercfgfile", "serverinfo", "setdemoinfo", "setinfo", "setmaster", "showinfo", "showpause", "showram", "shutdownserver", "sizedown", "sizeup", "skill", "skin", "sk_12mm_bullet1", "sk_12mm_bullet2", "sk_12mm_bullet3", "sk_9mmAR_bullet1", "sk_9mmAR_bullet2", "sk_9mmAR_bullet3", "sk_9mm_bullet1", "sk_9mm_bullet2", "sk_9mm_bullet3", "sk_agrunt_dmg_punch1", "sk_agrunt_dmg_punch2", "sk_agrunt_dmg_punch3", "sk_agrunt_health1", "sk_agrunt_health2", "sk_agrunt_health3", "sk_apache_health1", "sk_apache_health2", "sk_apache_health3", "sk_barney_health1", "sk_barney_health2", "sk_barney_health3",
          "sk_battery1", "sk_battery2", "sk_battery3", "sk_bigmomma_dmg_blast1", "sk_bigmomma_dmg_blast2", "sk_bigmomma_dmg_blast3", "sk_bigmomma_dmg_slash1", "sk_bigmomma_dmg_slash2", "sk_bigmomma_dmg_slash3", "sk_bigmomma_health_factor1", "sk_bigmomma_health_factor2", "sk_bigmomma_health_factor3", "sk_bigmomma_radius_blast1", "sk_bigmomma_radius_blast2", "sk_bigmomma_radius_blast3", "sk_bullsquid_dmg_bite1", "sk_bullsquid_dmg_bite2", "sk_bullsquid_dmg_bite3", "sk_bullsquid_dmg_spit1", "sk_bullsquid_dmg_spit2", "sk_bullsquid_dmg_spit3", "sk_bullsquid_dmg_whip1", "sk_bullsquid_dmg_whip2", "sk_bullsquid_dmg_whip3", "sk_bullsquid_health1", "sk_bullsquid_health2", "sk_bullsquid_health3", "sk_controller_dmgball1", "sk_controller_dmgball2", "sk_controller_dmgball3", "sk_controller_dmgzap1", "sk_controller_dmgzap2", "sk_controller_dmgzap3",
           "sk_controller_health1", "sk_controller_health2", "sk_controller_health3", "sk_controller_speedball1", "sk_controller_speedball2", "sk_controller_speedball3", "sk_gargantua_dmg_fire1", "sk_gargantua_dmg_fire2", "sk_gargantua_dmg_fire3", "sk_gargantua_dmg_slash1", "sk_gargantua_dmg_slash2", "sk_gargantua_dmg_slash3", "sk_gargantua_dmg_stomp1", "sk_gargantua_dmg_stomp2", "sk_gargantua_dmg_stomp3", "sk_gargantua_health1", "sk_gargantua_health2", "sk_gargantua_health3", "sk_hassassin_health1", "sk_hassassin_health2", "sk_hassassin_health3", "sk_headcrab_dmg_bite1", "sk_headcrab_dmg_bite2", "sk_headcrab_dmg_bite3", "sk_headcrab_health1", "sk_headcrab_health2", "sk_headcrab_health3", "sk_healthcharger1", "sk_healthcharger2", "sk_healthcharger3", "sk_healthkit1", "sk_healthkit2", "sk_healthkit3", "sk_hgrunt_gspeed1", "sk_hgrunt_gspeed2",
            "sk_hgrunt_gspeed3", "sk_hgrunt_health1", "sk_hgrunt_health2", "sk_hgrunt_health3", "sk_hgrunt_kick1", "sk_hgrunt_kick2", "sk_hgrunt_kick3", "sk_hgrunt_pellets1", "sk_hgrunt_pellets2", "sk_hgrunt_pellets3", "sk_hornet_dmg1", "sk_hornet_dmg2", "sk_hornet_dmg3", "sk_houndeye_dmg_blast1", "sk_houndeye_dmg_blast2", "sk_houndeye_dmg_blast3", "sk_houndeye_health1", "sk_houndeye_health2", "sk_houndeye_health3", "sk_ichthyosaur_health1", "sk_ichthyosaur_health2", "sk_ichthyosaur_health3", "sk_ichthyosaur_shake1", "sk_ichthyosaur_shake2", "sk_ichthyosaur_shake3", "sk_islave_dmg_claw1", "sk_islave_dmg_claw2", "sk_islave_dmg_claw3", "sk_islave_dmg_clawrake1", "sk_islave_dmg_clawrake2", "sk_islave_dmg_clawrake3", "sk_islave_dmg_zap1", "sk_islave_dmg_zap2", "sk_islave_dmg_zap3", "sk_islave_health1", "sk_islave_health2", "sk_islave_health3", "sk_leech_dmg_bite1",
             "sk_leech_dmg_bite2", "sk_leech_dmg_bite3", "sk_leech_health1", "sk_leech_health2", "sk_leech_health3", "sk_miniturret_health1", "sk_miniturret_health2", "sk_miniturret_health3", "sk_monster_arm1", "sk_monster_arm2", "sk_monster_arm3", "sk_monster_chest1", "sk_monster_chest2", "sk_monster_chest3", "sk_monster_head1", "sk_monster_head2", "sk_monster_head3", "sk_monster_leg1", "sk_monster_leg2", "sk_monster_leg3", "sk_monster_stomach1", "sk_monster_stomach2", "sk_monster_stomach3", "sk_nihilanth_health1", "sk_nihilanth_health2", "sk_nihilanth_health3", "sk_nihilanth_zap1", "sk_nihilanth_zap2", "sk_nihilanth_zap3", "sk_player_arm1", "sk_player_arm2", "sk_player_arm3", "sk_player_chest1", "sk_player_chest2", "sk_player_chest3", "sk_player_head1", "sk_player_head2", "sk_player_head3", "sk_player_leg1", "sk_player_leg2", "sk_player_leg3", "sk_player_stomach1",
              "sk_player_stomach2", "sk_player_stomach3", "sk_plr_357_bullet1", "sk_plr_357_bullet2", "sk_plr_357_bullet3", "sk_plr_9mmAR_bullet1", "sk_plr_9mmAR_bullet2", "sk_plr_9mmAR_bullet3", "sk_plr_9mmAR_grenade1", "sk_plr_9mmAR_grenade2", "sk_plr_9mmAR_grenade3", "sk_plr_9mm_bullet1", "sk_plr_9mm_bullet2", "sk_plr_9mm_bullet3", "sk_plr_buckshot1", "sk_plr_buckshot2", "sk_plr_buckshot3", "sk_plr_crowbar1", "sk_plr_crowbar2", "sk_plr_crowbar3", "sk_plr_egon_narrow1", "sk_plr_egon_narrow2", "sk_plr_egon_narrow3", "sk_plr_egon_wide1", "sk_plr_egon_wide2", "sk_plr_egon_wide3", "sk_plr_gauss1", "sk_plr_gauss2", "sk_plr_gauss3", "sk_plr_hand_grenade1", "sk_plr_hand_grenade2", "sk_plr_hand_grenade3", "sk_plr_rpg1", "sk_plr_rpg2", "sk_plr_rpg3", "sk_plr_satchel1", "sk_plr_satchel2", "sk_plr_satchel3", "sk_plr_tripmine1", "sk_plr_tripmine2", "sk_plr_tripmine3", "sk_plr_xbow_bolt_client1",
               "sk_plr_xbow_bolt_client2", "sk_plr_xbow_bolt_client3", "sk_plr_xbow_bolt_monster1", "sk_plr_xbow_bolt_monster2", "sk_plr_xbow_bolt_monster3", "sk_scientist_heal1", "sk_scientist_heal2", "sk_scientist_heal3", "sk_scientist_health1", "sk_scientist_health2", "sk_scientist_health3", "sk_sentry_health1", "sk_sentry_health2", "sk_sentry_health3", "sk_snark_dmg_bite1", "sk_snark_dmg_bite2", "sk_snark_dmg_bite3", "sk_snark_dmg_pop1", "sk_snark_dmg_pop2", "sk_snark_dmg_pop3", "sk_snark_health1", "sk_snark_health2", "sk_snark_health3", "sk_suitcharger1", "sk_suitcharger2", "sk_suitcharger3", "sk_turret_health1", "sk_turret_health2", "sk_turret_health3", "sk_zombie_dmg_both_slash1", "sk_zombie_dmg_both_slash2", "sk_zombie_dmg_both_slash3", "sk_zombie_dmg_one_slash1", "sk_zombie_dmg_one_slash2", "sk_zombie_dmg_one_slash3", "sk_zombie_health1", "sk_zombie_health2", "sk_zombie_health3",
                "slist", "slot1", "slot10", "slot2", "slot3", "slot4", "slot5", "slot6", "slot7", "slot8", "slot9", "snapshot", "snapto", "snd_noextraupdate", "snd_show", "soundfade", "soundinfo", "soundlist", "spawn", "speak", "special", "spectator", "spk", "startdemos", "startmovie", "status", "stop", "stopdemo", "stopsound", "stuffcmds", "suitvolume", "sv_accelerate", "sv_aim", "sv_airaccelerate", "sv_airmove", "sv_allowdownload", "sv_allowupload", "sv_allow_download", "sv_allow_upload", "sv_bounce", "sv_challengetime", "sv_cheats", "sv_clienttrace", "sv_clipmode", "sv_contact", "sv_failuretime", "sv_filterban", "sv_friction", "sv_gravity", "sv_instancedbaseline", "sv_lan", "sv_logrelay", "sv_maxrate", "sv_maxspectators", "sv_maxspeed", "sv_maxunlag", "sv_maxupdaterate", "sv_maxvelocity", "sv_minrate", "sv_minupdaterate", "sv_newunit", "sv_password", "sv_skycolor_b", "sv_skycolor_g", "sv_skycolor_r",
                 "sv_skyname", "sv_skyvec_x", "sv_skyvec_y", "sv_skyvec_z", "sv_spectalk", "sv_spectatormaxspeed", "sv_spectator_password", "sv_stepsize", "sv_stopspeed", "sv_timeout", "sv_unlag", "sv_unlagpush", "sv_unlagsamples", "sv_wateraccelerate", "sv_wateramp", "sv_waterfriction", "sv_zmax", "swapdemo", "sys_ticrate", "s_2dvolume", "s_a3d", "s_automax_distance", "s_automin_distance", "s_blipdir", "s_bloat", "s_buffersize", "s_disable_a3d", "s_distance", "s_doppler", "s_eax", "s_enable_a3d", "s_geometry", "s_leafnum", "s_materials", "s_max_distance", "s_min_distance", "s_numpolys", "s_occfactor", "s_occlude", "s_occ_epsilon", "s_polykeep", "s_polysize", "s_refdelay", "s_refgain", "s_reflect", "s_reverb", "s_rolloff", "s_show", "s_showtossed", "s_usepvs", "s_verbwet", "team", "team1_color", "team1_model", "team1_name", "team1_skin", "team2_color", "team2_model", "team2_name", "team2_skin", "tell", "texgamma",
                  "tfc_adminpwd", "tfc_autoteam", "tfc_balance_scores", "tfc_balance_teams", "tfc_clanbattle", "tfc_clanbattle_locked", "tfc_respawndelay", "thirdperson", "timedemo", "timerefresh", "togglebrowser", "toggleconsole", "topcolor", "traceralpha", "tracerblue", "tracergreen", "tracerlength", "traceroffset", "tracerred", "tracerspeed", "tracker", "unbind", "unbindall", "upload", "uprate", "user", "users", "version", "vgui_emulatemouse", "vid_d3d", "vid_describemode", "viewframe", "viewmodel", "viewnext", "viewprev", "viewsize", "violence_ablood", "violence_agibs", "violence_hblood", "violence_hgibs", "volume", "v_centermove", "v_centerspeed", "v_dark", "wait", "waterroom_type", "weapon_357", "weapon_9mmAR", "weapon_9mmhandgun", "weapon_crossbow", "weapon_crowbar", "weapon_displacer", "weapon_eagle", "weapon_egon", "weapon_gauss", "weapon_grapple", "weapon_handgrenade", "weapon_hornetgun", "weapon_knife",
                   "weapon_m249", "weapon_pipewrench", "weapon_rpg", "weapon_satchel", "weapon_shockrifle", "weapon_shotgun", "weapon_snark", "weapon_sniperrifle", "weapon_sporelauncher", "weapon_tripmine", "writeid", "writeip", "zoom_sensitivity_ratio", "_snd_mixahead", "bxt_autopause", "w <number>", "bxt_interprocess_enable", "_bxt_interprocess_reset", "bxt_timer_autostop", "bxt_timer_start", "bxt_timer_stop", "bxt_timer_reset", "_bxt_bunnysplit_time_update_frequency", "bxt_record <filename>", "bxt_autorecord <filename>", "bxt_ch_set_armor <armor>", "bxt_ch_set_health <health>", "bxt_ch_set_pos <x> <y> <z>", "bxt_ch_set_pos_offset <dx> <dy> <dz>", "bxt_ch_set_vel <vx> <vy> <vz>", "bxt_ch_set_vel_angles <magnitude>", "bxt_ch_set_vel_angles <pitch> <yaw> <magnitude>", "bxt_novis", "bxt_wallhack", "bxt_wallhack_additive", "bxt_wallhack_alpha <alpha>", "bxt_bhopcap", "bxt_bhopcap_prediction", "+bxt_tas_autojump", "+bxt_tas_ducktap",
                    "+bxt_tas_jumpbug", "bxt_autojump", "bxt_autojump_prediction", "bxt_fade_remove", "bxt_show_triggers", "bxt_show_hidden_entities", "bxt_show_nodes", "bxt_freecam <0|1>", "bxt_collision_depth_map", "bxt_collision_depth_map_max_depth", "bxt_collision_depth_map_colors", "bxt_collision_depth_map_hull", "bxt_collision_depth_map_pixel_scale <scale>", "bxt_collision_depth_map_remove_distance_limit <0|1>", "bxt_cam_fixed <x> <y> <z> <pitch> <yaw> <roll>", "bxt_cam_offset <x> <y> <z> <pitch> <yaw> <roll>", "bxt_cam_clear", "bxt_show_triggers_legacy", "_bxt_min_frametime", "_bxt_norefresh", "bxt_hud", "bxt_hud_color", "bxt_hud_precision", "bxt_hud_useables_radius", "bxt_hud_distance", "bxt_hud_entity_hp", "bxt_hud_jumpspeed", "bxt_hud_origin", "bxt_hud_selfgauss", "bxt_hud_speedometer", "bxt_hud_health", "bxt_hud_nihilanth", "bxt_hud_tas_editor_status", "bxt_hud_timer", "bxt_hud_useables", "bxt_hud_velocity", "bxt_hud_viewangles",
                     "bxt_hud_visible_landmarks", "bxt_tas_loadscript <filename>", "bxt_tas_new <filename> <starting command> <FPS>", "bxt_tas_norefresh_until_last_frames", "bxt_tas_playback_speed <speed>", "bxt_tas_split <filename>", "_bxt_map", "_bxt_load", "bxt_tas_exportscript", "_bxt_reset_frametime_remainder", "bxt_taslog <0|1>", "bxt_taslog_filename <filename>", "bxt_tas_write_log <0|1>", "bxt_tas_editor <0|1|2>", "bxt_tas_editor_save", "bxt_tas_editor_set_run_point_and_save", "bxt_tas_editor_toggle <what>", "bxt_tas_editor_insert_point", "bxt_tas_editor_delete_point", "bxt_tas_editor_delete_last_point", "bxt_tas_editor_set_yaw <yaw>", "bxt_tas_editor_unset_yaw", "bxt_tas_editor_set_pitch <pitch>", "bxt_tas_editor_unset_pitch", "bxt_tas_editor_set_repeats <repeats>", "bxt_tas_editor_simulate_for_ms <ms>"]);