export default [
  {
    id: "70",
    name: "Half-Life",
    iconFile: "hl1.ico",
    background: "half-life-background.jpg",
    needSteam: true,
    info: {
      isStandalone: true,
      requiredGame: null,
      installPath: "",
      removePaths: ["Half-Life"],
      size: 429,
      archive: 227,
      features: [
        "#UI_WON",
        "#UI_STEAM",
        "Edited DLL with HUD settings",
        "Bunnymod XT",
        "#UI_LIVESPLIT",
        "RInput",
      ],
      url: "https://hlsr.pro/downloadable/Half-Life.zip",
      sourceruns: "https://wiki.sourceruns.org/wiki/Category:Half-Life_1",
    },
  },
  {
    id: "50",
    name: "Half-Life: Opposing Force",
    iconFile: "of.ico",
    background: "opposing-force-background.jpg",
    needSteam: true,
    info: {
      isStandalone: false,
      requiredGame: "70",
      installPath: "Half-Life",
      removePaths: ["Half-Life/gearbox", "Half-Life/gearbox_WON"],
      size: 513,
      archive: 269,
      features: [
        "#UI_WON",
        "#UI_STEAM",
        "Bunnymod XT",
        "#UI_LIVESPLIT",
        "RInput",
      ],
      url: "https://hlsr.pro/downloadable/Opposing-Force.zip",
      sourceruns: "https://wiki.sourceruns.org/wiki/Category:Opposing_Force",
    },
  },
  {
    id: "130",
    name: "Half-Life: Blue Shift",
    iconFile: "bs.ico",
    background: "blue-shift-background.jpg",
    needSteam: true,
    info: {
      isStandalone: false,
      requiredGame: "70",
      installPath: "Half-Life",
      removePaths: ["Half-Life/bshift"],
      size: 285,
      archive: 168,
      features: ["#UI_STEAM", "Bunnymod XT", "#UI_LIVESPLIT", "RInput"],
      url: "https://hlsr.pro/downloadable/Blue-Shift.zip",
      sourceruns: "https://wiki.sourceruns.org/wiki/Category:Blue_Shift",
    },
  },
  {
    id: "220",
    name: "Half-Life 2",
    iconFile: "hl2.ico",
    background: "half-life-2-background.jpg",
    needSteam: false,
    info: {
      isStandalone: true,
      requiredGame: null,
      installPath: "",
      removePaths: ["Half-Life 2"],
      size: 3464,
      archive: 1950,
      features: [
        "Source Unpack (New Engine)",
        "Source Pause Tool",
        "LiveSplit with splits",
        "RInput",
      ],
      url:
        "https://github.com/InfiniteC0re/HLSR/releases/download/HL2/Half-Life.2.zip",
      sourceruns: "https://wiki.sourceruns.org/wiki/Category:Half-Life_2",
    },
  },
  {
    id: "218",
    name: "Half-Life 2: Ghosting",
    iconFile: "hl2.ico",
    background: "half-life-2-ghosting-background.jpg",
    needSteam: false,
    info: {
      isStandalone: true,
      requiredGame: null,
      installPath: "",
      removePaths: ["Ghosting"],
      size: 4933,
      archive: 2890,
      features: [
        "Ghosting Mod",
        "Cutsceneless Mod",
        "Half-Life 1 Movement Mod",
        "#UI_LIVESPLIT",
        "RInput",
      ],
      url: "http://194.87.95.20/games/Ghosting.zip",
      sourceruns: "https://wiki.sourceruns.org/wiki/Ghosting_mod",
    },
  },
];
